---

- name: Check if selinux is running
  command: getenforce
  register: sestatus
  changed_when: false

- name: Install libselinux-python
  yum: name=libselinux-python state=present

- name: Install Repository
  yum: name={{ item }} state=present
  with_items:
    - epel-release
    - http://rpms.famillecollet.com/enterprise/remi-release-6.rpm

- replace: dest=/etc/yum.repos.d/{{ item }} regexp="enabled *= *1" replace="enabled=0"
  with_items:
    - epel.repo
    - remi.repo

- replace: dest=/etc/yum.repos.d/{{ item }} regexp="#baseurl=" replace="baseurl="
  with_items:
    - epel.repo
    - remi.repo
