---

- name: Install Repository
  yum: name={{ item }} state=present
  with_items:
    - http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm

- name: Install nginx
  yum: name=nginx state=present  enablerepo=nginx

- name: Copy nginx configuration for wordpress
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx

# - replace: dest=/etc/yum.repos.d/{{ item }} regexp="enabled *= *1" replace="enabled=0"
#   with_items:
#     - epel.repo
#     - remi.repo
#
# - name: Install nginx
#   yum: name=nginx state=present  enablerepo=remi
#
# - name: Copy nginx configuration for wordpress
#   template: src=default.conf dest=/etc/nginx/conf.d/default.conf
#   notify: restart nginx
